name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        default: true
        required: true
        description: "Create a GitHub release"
      release_tag:
        type: string
        required: true
        description: "Tag for GitHub release"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.x]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install essentials
        run: pip install -U --user setuptools twine wheel

      - name: Build
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload --skip-existing dist/*
          tar -cavf dist.tar.gz dist

      - name: GitHub release (from tag)
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: dist.tar.gz
          overwrite: true

      - name: GitHub release (manual)
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.release }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: dist.tar.gz
          tag: ${{ inputs.release_tag }}
          overwrite: true
